[package]
name = "immigrant-cli"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
ass-stroke.workspace = true
file-diffs.workspace = true
generator-postgres.workspace = true
schema.workspace = true
