[package]
name = "immigrant-file-diffs"
version.workspace = true
edition.workspace = true

[dependencies]
imara-diff.workspace = true
ouroboros.workspace = true
patch.workspace = true
thiserror.workspace = true
