[package]
name = "immigrant-dmdl"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
file-diffs.workspace = true
schema.workspace = true
cli.workspace = true
